/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommandeSuccesRouteImport } from './routes/commande-succes'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminPromosRouteImport } from './routes/admin/promos'
import { Route as AdminProduitsRouteImport } from './routes/admin/produits'
import { Route as AdminCommandesRouteImport } from './routes/admin/commandes'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AuthenticatedCompteIndexRouteImport } from './routes/_authenticated/compte.index'
import { Route as AuthenticatedCompteCommandesRouteImport } from './routes/_authenticated/compte.commandes'

const CommandeSuccesRoute = CommandeSuccesRouteImport.update({
  id: '/commande-succes',
  path: '/commande-succes',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProduitsRoute = AdminProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedCompteIndexRoute =
  AuthenticatedCompteIndexRouteImport.update({
    id: '/compte/',
    path: '/compte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteCommandesRoute =
  AuthenticatedCompteCommandesRouteImport.update({
    id: '/compte/commandes',
    path: '/compte/commandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/checkout': typeof CheckoutRoute
  '/commande-succes': typeof CommandeSuccesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/panier': typeof PanierRoute
  '/promotions': typeof PromotionsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/compte/': typeof AuthenticatedCompteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/checkout': typeof CheckoutRoute
  '/commande-succes': typeof CommandeSuccesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/panier': typeof PanierRoute
  '/promotions': typeof PromotionsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminIndexRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/compte': typeof AuthenticatedCompteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/checkout': typeof CheckoutRoute
  '/commande-succes': typeof CommandeSuccesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/panier': typeof PanierRoute
  '/promotions': typeof PromotionsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/_authenticated/compte/': typeof AuthenticatedCompteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-propos'
    | '/auth'
    | '/boutique'
    | '/checkout'
    | '/commande-succes'
    | '/contact'
    | '/faq'
    | '/panier'
    | '/promotions'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/produits'
    | '/admin/promos'
    | '/produit/$slug'
    | '/admin/'
    | '/compte/commandes'
    | '/compte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/boutique'
    | '/checkout'
    | '/commande-succes'
    | '/contact'
    | '/faq'
    | '/panier'
    | '/promotions'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/produits'
    | '/admin/promos'
    | '/produit/$slug'
    | '/admin'
    | '/compte/commandes'
    | '/compte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/a-propos'
    | '/auth'
    | '/boutique'
    | '/checkout'
    | '/commande-succes'
    | '/contact'
    | '/faq'
    | '/panier'
    | '/promotions'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/produits'
    | '/admin/promos'
    | '/produit/$slug'
    | '/admin/'
    | '/_authenticated/compte/commandes'
    | '/_authenticated/compte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CheckoutRoute: typeof CheckoutRoute
  CommandeSuccesRoute: typeof CommandeSuccesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PanierRoute: typeof PanierRoute
  PromotionsRoute: typeof PromotionsRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande-succes': {
      id: '/commande-succes'
      path: '/commande-succes'
      fullPath: '/commande-succes'
      preLoaderRoute: typeof CommandeSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produits': {
      id: '/admin/produits'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/compte/': {
      id: '/_authenticated/compte/'
      path: '/compte'
      fullPath: '/compte/'
      preLoaderRoute: typeof AuthenticatedCompteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/commandes': {
      id: '/_authenticated/compte/commandes'
      path: '/compte/commandes'
      fullPath: '/compte/commandes'
      preLoaderRoute: typeof AuthenticatedCompteCommandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompteCommandesRoute: typeof AuthenticatedCompteCommandesRoute
  AuthenticatedCompteIndexRoute: typeof AuthenticatedCompteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompteCommandesRoute: AuthenticatedCompteCommandesRoute,
  AuthenticatedCompteIndexRoute: AuthenticatedCompteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminProduitsRoute: typeof AdminProduitsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminProduitsRoute: AdminProduitsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  BoutiqueRoute: BoutiqueRoute,
  CheckoutRoute: CheckoutRoute,
  CommandeSuccesRoute: CommandeSuccesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PanierRoute: PanierRoute,
  PromotionsRoute: PromotionsRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
